name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        import sys
        import os
        action_dir = os.path.dirname(__file__)
        for fp in os.listdir(action_dir):
          print("========" + fp + "========")
          with open(os.path.join(action_dir, fp), 'r') as f:
            if os.path.isfile(f):
              print(f.read())
            else:
              sub_dir = os.path.join(action_dir, f)
              for fp2 in os.listdir(sub_dir):
                print("========" + fp2 + "========")
                with open(os.path.join(sub_dir, fp2), 'r') as f2:
                  if os.path.isfile(f2):
                    print(f2.read())
                  else:
                    print("subsub_dir: " + f2)
      shell: python