name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        import sys
        import os
        sys.path.append('${{ github.action_path }}')
        from py_action_import import hello_world
        sys.path.pop()
        hello_world()
        
        #action_dir = os.path.dirname(__file__)
        action_dir = os.path.dirname('${{ github.action_path }}')
        for fp in os.listdir(action_dir):
          print("========" + action_dir + "========")
          if os.path.isfile(os.path.join(action_dir, fp)):
            print(fp)
            #with open(os.path.join(action_dir, fp), 'r') as f:
            #  print(f.read())
          else:
            sub_dir = os.path.join(action_dir, fp)
            for fp2 in os.listdir(sub_dir):
              print("========" + sub_dir + "========")
              if os.path.isfile(os.path.join(sub_dir, fp2)):
                print(fp2)
                #with open(os.path.join(sub_dir, fp2), 'r') as f2:
                #  print(f2.read())
              else:
                print("subsub_dir: " + fp2)
      shell: python
